
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 05 16:08:50 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 30;
  public static final int LBRACKET = 32;
  public static final int CHAR = 45;
  public static final int CONST = 13;
  public static final int SEMI = 39;
  public static final int LPAREN = 34;
  public static final int CONTINUE = 12;
  public static final int MINUS = 17;
  public static final int RPAREN = 35;
  public static final int AND = 22;
  public static final int LT = 29;
  public static final int OR = 23;
  public static final int COMMA = 40;
  public static final int CLASS = 6;
  public static final int INC = 24;
  public static final int DIV = 19;
  public static final int PLUS = 18;
  public static final int IF = 15;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 38;
  public static final int RBRACKET = 33;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int EQEQ = 31;
  public static final int NUMBER = 42;
  public static final int MOD = 21;
  public static final int NEQ = 26;
  public static final int IDENT = 43;
  public static final int BREAK = 14;
  public static final int VOID = 5;
  public static final int GTE = 28;
  public static final int LBRACE = 36;
  public static final int ELSE = 16;
  public static final int READ = 8;
  public static final int WHILE = 10;
  public static final int RBRACE = 37;
  public static final int BOOLCONST = 44;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int DEC = 25;
  public static final int GT = 27;
  public static final int PRINT = 3;
  public static final int DO = 9;
}

